### ISSUE TITLE
[BUG] JavaScript error

### ISSUE THREAD

**Issue by KITT3000** [jtsage/FS19_Mod_Checker#27]
**Describe the bug**
JS error message window.

**To Reproduce**
1. Load the gameSettings.xml configuration file or folder
2. Click on 'Scan'
3. Wait a few seconds (Process: Reading)

**Expected behavior**
Loading and checking for errors in the log

**Screenshots**
![image](https://user-images.githubusercontent.com/2678653/121789485-9220e000-cbd6-11eb-8f4d-d6810e889324.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (20H2 build 19042.1052)
 - ModChecker v1.9.18

**Additional context**
The problem only occurs in 1 case, with my mod folder in which I have a lot of unpacked mod files (some may be duplicated under, one as a different folder with the same name as the ZIP archive) and the mod testing program from Giantsa (TestRunner) but I checked and without it the problem still appears, other folders with mods (in 99% only ZIP archives) load in the program without any problem.
Here is the contents of my folder where this error occurs:
![image](https://user-images.githubusercontent.com/2678653/121789740-c09fba80-cbd8-11eb-9368-05a0af5bba6d.png)
![image](https://user-images.githubusercontent.com/2678653/121789744-cbf2e600-cbd8-11eb-9855-9684e7caa777.png)
![image](https://user-images.githubusercontent.com/2678653/121789751-d614e480-cbd8-11eb-8396-8c0da68f3da8.png)
![image](https://user-images.githubusercontent.com/2678653/121789754-d9a86b80-cbd8-11eb-8baa-ef32bd7de9f3.png)

**Comment by jtsage** [comment]
Working on a fix right now.  It almost has to be a zipped mod with a CRC error on the modDesc.xml file - that seems to be the sole place in the entire tree that "Invalid CRC" exists as an error string.

That said, I do wish node modules had better documentation.  Also, if you re-run the program on 1.9.19, and it picks up a crc error (It'll be in the debug log CTRL+ALT+D), I would *love* to have a copy of the offending file if possible.  Mostly because it's a great test, and I want to see how FS actually handles that.

**Comment by KITT3000** [comment]
The LOG from the program is empty, it displays nothing, and the folder has been loaded correctly.

**Comment by jtsage** [comment]
1.) the log.  I bet it doesn't auto update that window, ever.  It probably should. Note for 1.9.20

2.) I found a copy of that file, complete with CRC errors.  Excellent :)
